// <auto-generated />
namespace HeatChart.Data.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewChanges_Dimension_11182017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewChanges_Dimension_11182017));
        
        string IMigrationMetadata.Id
        {
            get { return "201711181451321_NewChanges_Dimension_11182017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
